// ========================================================================
// SISTEMA DE GESTÃO — CAMILA RODRIGUES BEAUTY STUDIO
// Seed Data: src/lib/mockSeedData.ts
// ========================================================================

import { format, subDays, addDays, setHours, setMinutes } from 'date-fns';
import {
  Profile,
  StudioSettings,
  ServiceCategory,
  Service,
  PaymentMethod,
  ExpenseCategory,
  Client,
  Appointment,
  FinancialEntry,
  FinancialExpense,
  AppNotification,
  AuditLog,
  GoogleCalendarConnection,
} from '../types';

export const initialProfile: Profile = {
  id: 'usr_camila_01',
  email: 'camila@camilarodriguesbeauty.com.br',
  full_name: 'Camila Rodrigues',
  role: 'admin',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=250&auto=format&fit=crop',
  created_at: '2026-01-10T10:00:00Z',
  updated_at: '2026-09-08T12:00:00Z',
};

export const initialStudioSettings: StudioSettings = {
  id: 'set_studio_01',
  user_id: 'usr_camila_01',
  studio_name: 'Camila Rodrigues Beauty Studio',
  phone: '(11) 94107-0247',
  whatsapp: '5511941070247',
  email: 'contato@camilarodriguesbeauty.com.br',
  address: 'Rua Cristiano Angeli, 1514 A — Bairro Assunção, São Bernardo do Campo - SP',
  instagram: '@lashcamilarodrigues',
  currency: 'BRL',
  timezone: 'America/Sao_Paulo',
  default_appointment_interval: 15,
  auto_generate_financial_entry: true,
  business_hours: {
    monday: { open: '09:00', close: '19:00', isOpen: true, lunchStart: '12:30', lunchEnd: '13:30' },
    tuesday: { open: '09:00', close: '19:00', isOpen: true, lunchStart: '12:30', lunchEnd: '13:30' },
    wednesday: { open: '09:00', close: '19:00', isOpen: true, lunchStart: '12:30', lunchEnd: '13:30' },
    thursday: { open: '09:00', close: '19:00', isOpen: true, lunchStart: '12:30', lunchEnd: '13:30' },
    friday: { open: '09:00', close: '19:00', isOpen: true, lunchStart: '12:30', lunchEnd: '13:30' },
    saturday: { open: '09:00', close: '17:00', isOpen: true, lunchStart: '12:00', lunchEnd: '13:00' },
    sunday: { open: '09:00', close: '13:00', isOpen: false, lunchStart: null, lunchEnd: null },
  },
  created_at: '2026-01-10T10:00:00Z',
  updated_at: '2026-09-08T12:00:00Z',
};

export const initialServiceCategories: ServiceCategory[] = [
  { id: 'cat_cilios', user_id: 'usr_camila_01', name: 'Extensão de Cílios', description: 'Técnicas nobres e visagismo do olhar', is_active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'cat_sobrancelhas', user_id: 'usr_camila_01', name: 'Sobrancelhas & Visagismo', description: 'Harmonização facial e design', is_active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'cat_cursos', user_id: 'usr_camila_01', name: 'Cursos & Mentorias', description: 'Capacitação e técnicas avançadas', is_active: true, created_at: '2026-01-10T10:00:00Z' },
];

export const initialServices: Service[] = [
  {
    id: 'srv_cristal',
    user_id: 'usr_camila_01',
    category_id: 'cat_cilios',
    name: 'Volume Cristal',
    description: 'Efeito rímel refinado e ultra natural para o dia a dia.',
    price: 120.00,
    duration_minutes: 120,
    maintenance_price: 75.00,
    maintenance_duration_minutes: 90,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  },
  {
    id: 'srv_esmeralda',
    user_id: 'usr_camila_01',
    category_id: 'cat_cilios',
    name: 'Volume Esmeralda',
    description: 'Volume suave com preenchimento harmonioso e acabamento aveludado.',
    price: 125.00,
    duration_minutes: 120,
    maintenance_price: 80.00,
    maintenance_duration_minutes: 90,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  },
  {
    id: 'srv_jade',
    user_id: 'usr_camila_01',
    category_id: 'cat_cilios',
    name: 'Volume Jade',
    description: 'Densidade equilibrada com fios ultra macios e alinhamento impecável.',
    price: 135.00,
    duration_minutes: 130,
    maintenance_price: 85.00,
    maintenance_duration_minutes: 90,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  },
  {
    id: 'srv_rubi',
    user_id: 'usr_camila_01',
    category_id: 'cat_cilios',
    name: 'Volume Rubi',
    description: 'Volume expressivo com efeito delineado e densidade marcante.',
    price: 145.00,
    duration_minutes: 140,
    maintenance_price: 90.00,
    maintenance_duration_minutes: 100,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  },
  {
    id: 'srv_perola',
    user_id: 'usr_camila_01',
    category_id: 'cat_cilios',
    name: 'Volume Pérola (VIP)',
    description: 'Efeito Fox Eyes sofisticado e olhar luxuosamente alongado.',
    price: 150.00,
    duration_minutes: 150,
    maintenance_price: 95.00,
    maintenance_duration_minutes: 100,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
  },
];

export const initialPaymentMethods: PaymentMethod[] = [
  { id: 'pm_pix', user_id: 'usr_camila_01', name: 'Pix', is_active: true },
  { id: 'pm_credito', user_id: 'usr_camila_01', name: 'Cartão de Crédito', is_active: true },
  { id: 'pm_debito', user_id: 'usr_camila_01', name: 'Cartão de Débito', is_active: true },
  { id: 'pm_dinheiro', user_id: 'usr_camila_01', name: 'Dinheiro em Espécie', is_active: true },
  { id: 'pm_transferencia', user_id: 'usr_camila_01', name: 'Transferência Bancária', is_active: true },
];

export const initialExpenseCategories: ExpenseCategory[] = [
  { id: 'exp_aluguel', user_id: 'usr_camila_01', name: 'Aluguel & Condomínio', cost_type: 'fixed', is_active: true },
  { id: 'exp_internet', user_id: 'usr_camila_01', name: 'Internet & Telefonia', cost_type: 'fixed', is_active: true },
  { id: 'exp_energia', user_id: 'usr_camila_01', name: 'Energia Elétrica', cost_type: 'fixed', is_active: true },
  { id: 'exp_agua', user_id: 'usr_camila_01', name: 'Água & Saneamento', cost_type: 'fixed', is_active: true },
  { id: 'exp_contabilidade', user_id: 'usr_camila_01', name: 'Contabilidade & Sistemas', cost_type: 'fixed', is_active: true },
  { id: 'exp_materiais', user_id: 'usr_camila_01', name: 'Materiais & Colas', cost_type: 'variable', is_active: true },
  { id: 'exp_fios', user_id: 'usr_camila_01', name: 'Fios & Descartáveis', cost_type: 'variable', is_active: true },
  { id: 'exp_marketing', user_id: 'usr_camila_01', name: 'Marketing & Tráfego Pago', cost_type: 'variable', is_active: true },
  { id: 'exp_impostos', user_id: 'usr_camila_01', name: 'Impostos & Taxas', cost_type: 'variable', is_active: true },
  { id: 'exp_transporte', user_id: 'usr_camila_01', name: 'Transporte & Combustível', cost_type: 'variable', is_active: true },
  { id: 'exp_equipamentos', user_id: 'usr_camila_01', name: 'Equipamentos & Ferramentas', cost_type: 'variable', is_active: true },
  { id: 'exp_manutencao', user_id: 'usr_camila_01', name: 'Manutenção do Espaço', cost_type: 'variable', is_active: true },
  { id: 'exp_cursos', user_id: 'usr_camila_01', name: 'Cursos & Especializações', cost_type: 'variable', is_active: true },
  { id: 'exp_outros', user_id: 'usr_camila_01', name: 'Outros Custos', cost_type: 'variable', is_active: true },
];

export const initialClients: Client[] = [
  {
    id: 'cli_01',
    user_id: 'usr_camila_01',
    full_name: 'Mariana Silva Santos',
    phone: '11987654321',
    whatsapp: '5511987654321',
    email: 'mariana.silva@email.com',
    birth_date: '1995-04-12',
    origin: 'Instagram',
    notes: 'Olhos sensíveis. Prefere curvatura D com efeito delineado suave.',
    status: 'active',
    first_visit_date: '2026-02-15',
    created_at: '2026-02-15T14:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 680.00,
    total_appointments: 5,
  },
  {
    id: 'cli_02',
    user_id: 'usr_camila_01',
    full_name: 'Beatriz Costa Lima',
    phone: '11976543210',
    whatsapp: '5511976543210',
    email: 'beatriz.costa@email.com',
    birth_date: '1998-08-24',
    origin: 'Indicação',
    notes: 'Adora o Volume Jade bem volumoso e alinhado.',
    status: 'active',
    first_visit_date: '2026-03-10',
    created_at: '2026-03-10T11:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 540.00,
    total_appointments: 4,
  },
  {
    id: 'cli_03',
    user_id: 'usr_camila_01',
    full_name: 'Juliana Mendes Rocha',
    phone: '11965432109',
    whatsapp: '5511965432109',
    email: 'juliana.mendes@email.com',
    birth_date: '1992-11-03',
    origin: 'Instagram',
    notes: 'Cliente do Volume Pérola VIP. Gosta do efeito Fox Eyes.',
    status: 'active',
    first_visit_date: '2026-04-05',
    created_at: '2026-04-05T09:30:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 740.00,
    total_appointments: 5,
  },
  {
    id: 'cli_04',
    user_id: 'usr_camila_01',
    full_name: 'Ana Carolina Ferreira',
    phone: '11954321098',
    whatsapp: '5511954321098',
    email: 'anacarol.f@email.com',
    birth_date: '2000-01-18',
    origin: 'Google',
    notes: 'Primeira vez fazendo extensão, prefere o Volume Cristal bem delicado.',
    status: 'active',
    first_visit_date: '2026-07-20',
    created_at: '2026-07-20T16:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 195.00,
    total_appointments: 2,
  },
  {
    id: 'cli_05',
    user_id: 'usr_camila_01',
    full_name: 'Gabriela Vasconcelos',
    phone: '11943210987',
    whatsapp: '5511943210987',
    email: 'gabi.vasconcelos@email.com',
    birth_date: '1996-06-30',
    origin: 'Instagram',
    notes: 'Fiel ao Volume Esmeralda. Sempre pontual.',
    status: 'active',
    first_visit_date: '2026-05-12',
    created_at: '2026-05-12T13:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 445.00,
    total_appointments: 4,
  },
  {
    id: 'cli_06',
    user_id: 'usr_camila_01',
    full_name: 'Fernanda de Oliveira',
    phone: '11932109876',
    whatsapp: '5511932109876',
    email: 'fernanda.oliveira@email.com',
    birth_date: '1994-09-15',
    origin: 'Passante',
    notes: 'Prefere atendimentos aos sábados pela manhã.',
    status: 'active',
    first_visit_date: '2026-06-01',
    created_at: '2026-06-01T10:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 325.00,
    total_appointments: 3,
  },
  {
    id: 'cli_07',
    user_id: 'usr_camila_01',
    full_name: 'Larissa Alcantara',
    phone: '11921098765',
    whatsapp: '5511921098765',
    email: 'larissa.alcantara@email.com',
    birth_date: '1997-12-08',
    origin: 'Instagram',
    notes: 'Volume Rubi marcante.',
    status: 'active',
    first_visit_date: '2026-08-10',
    created_at: '2026-08-10T15:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 235.00,
    total_appointments: 2,
  },
  {
    id: 'cli_08',
    user_id: 'usr_camila_01',
    full_name: 'Patrícia Nogueira',
    phone: '11910987654',
    whatsapp: '5511910987654',
    email: 'patricia.nog@email.com',
    birth_date: '1989-03-22',
    origin: 'Indicação',
    notes: 'Em pausa de procedimento para descanso dos fios.',
    status: 'inactive',
    first_visit_date: '2026-01-20',
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-09-08T12:00:00Z',
    total_spent: 280.00,
    total_appointments: 2,
  },
];

// Gerar datas relativas dinâmicas para a agenda
const today = new Date();
const todayStr = format(today, 'yyyy-MM-dd');

export const initialAppointments: Appointment[] = [
  // Hoje 09:00 - Mariana Silva (Volume Jade Manutenção)
  {
    id: 'app_01',
    user_id: 'usr_camila_01',
    client_id: 'cli_01',
    service_id: 'srv_jade',
    appointment_type: 'maintenance',
    start_time: setMinutes(setHours(today, 9), 0).toISOString(),
    end_time: setMinutes(setHours(today, 10), 30).toISOString(),
    duration_minutes: 90,
    total_amount: 85.00,
    deposit_amount: 0.00,
    remaining_amount: 85.00,
    payment_status: 'fully_paid',
    payment_method_id: 'pm_pix',
    status: 'completed',
    notes: 'Manutenção de 18 dias. Fios impecáveis.',
    google_event_id: 'gcal_evt_01',
    created_at: subDays(today, 3).toISOString(),
    updated_at: today.toISOString(),
  },
  // Hoje 11:00 - Beatriz Costa (Volume Esmeralda Manutenção)
  {
    id: 'app_02',
    user_id: 'usr_camila_01',
    client_id: 'cli_02',
    service_id: 'srv_esmeralda',
    appointment_type: 'maintenance',
    start_time: setMinutes(setHours(today, 11), 0).toISOString(),
    end_time: setMinutes(setHours(today, 12), 30).toISOString(),
    duration_minutes: 90,
    total_amount: 80.00,
    deposit_amount: 30.00,
    remaining_amount: 50.00,
    payment_status: 'deposit_paid',
    payment_method_id: 'pm_pix',
    status: 'confirmed',
    notes: 'Sinal de R$ 30 pago via Pix.',
    google_event_id: 'gcal_evt_02',
    created_at: subDays(today, 2).toISOString(),
    updated_at: today.toISOString(),
  },
  // Hoje 14:00 - Juliana Mendes (Volume Pérola VIP Aplicação)
  {
    id: 'app_03',
    user_id: 'usr_camila_01',
    client_id: 'cli_03',
    service_id: 'srv_perola',
    appointment_type: 'application',
    start_time: setMinutes(setHours(today, 14), 0).toISOString(),
    end_time: setMinutes(setHours(today, 16), 30).toISOString(),
    duration_minutes: 150,
    total_amount: 150.00,
    deposit_amount: 50.00,
    remaining_amount: 100.00,
    payment_status: 'deposit_paid',
    payment_method_id: 'pm_credito',
    status: 'scheduled',
    notes: 'Nova aplicação completa com mapping Fox Eyes.',
    google_event_id: 'gcal_evt_03',
    created_at: subDays(today, 1).toISOString(),
    updated_at: today.toISOString(),
  },
  // Hoje 17:00 - Gabriela Vasconcelos (Volume Cristal Aplicação)
  {
    id: 'app_04',
    user_id: 'usr_camila_01',
    client_id: 'cli_05',
    service_id: 'srv_cristal',
    appointment_type: 'application',
    start_time: setMinutes(setHours(today, 17), 0).toISOString(),
    end_time: setMinutes(setHours(today, 19), 0).toISOString(),
    duration_minutes: 120,
    total_amount: 120.00,
    deposit_amount: 0.00,
    remaining_amount: 120.00,
    payment_status: 'pending',
    payment_method_id: 'pm_pix',
    status: 'scheduled',
    notes: 'Confirmado pelo WhatsApp.',
    google_event_id: 'gcal_evt_04',
    created_at: subDays(today, 1).toISOString(),
    updated_at: today.toISOString(),
  },
  // Amanhã 10:00 - Ana Carolina (Volume Cristal Manutenção)
  {
    id: 'app_05',
    user_id: 'usr_camila_01',
    client_id: 'cli_04',
    service_id: 'srv_cristal',
    appointment_type: 'maintenance',
    start_time: setMinutes(setHours(addDays(today, 1), 10), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(today, 1), 11), 30).toISOString(),
    duration_minutes: 90,
    total_amount: 75.00,
    deposit_amount: 0.00,
    remaining_amount: 75.00,
    payment_status: 'pending',
    status: 'confirmed',
    notes: 'Manutenção 15 dias.',
    google_event_id: 'gcal_evt_05',
    created_at: subDays(today, 2).toISOString(),
    updated_at: today.toISOString(),
  },
  // Ontem 14:00 - Larissa Alcantara (Volume Rubi Aplicação - Concluído)
  {
    id: 'app_06',
    user_id: 'usr_camila_01',
    client_id: 'cli_07',
    service_id: 'srv_rubi',
    appointment_type: 'application',
    start_time: setMinutes(setHours(subDays(today, 1), 14), 0).toISOString(),
    end_time: setMinutes(setHours(subDays(today, 1), 16), 20).toISOString(),
    duration_minutes: 140,
    total_amount: 145.00,
    deposit_amount: 0.00,
    remaining_amount: 0.00,
    payment_status: 'fully_paid',
    payment_method_id: 'pm_pix',
    status: 'completed',
    notes: 'Resultado espetacular. Cliente amou.',
    google_event_id: 'gcal_evt_06',
    created_at: subDays(today, 4).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
];

export const initialFinancialEntries: FinancialEntry[] = [
  {
    id: 'ent_01',
    user_id: 'usr_camila_01',
    client_id: 'cli_01',
    service_id: 'srv_jade',
    appointment_id: 'app_01',
    description: 'Manutenção Volume Jade — Mariana Silva',
    category: 'service',
    amount: 85.00,
    payment_method_id: 'pm_pix',
    date: todayStr,
    status: 'received',
    notes: 'Pago no término do atendimento',
    created_at: today.toISOString(),
    updated_at: today.toISOString(),
  },
  {
    id: 'ent_02',
    user_id: 'usr_camila_01',
    client_id: 'cli_02',
    service_id: 'srv_esmeralda',
    appointment_id: 'app_02',
    description: 'Sinal de Agendamento — Beatriz Costa',
    category: 'deposit',
    amount: 30.00,
    payment_method_id: 'pm_pix',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    status: 'received',
    notes: 'Sinal garantidor de vaga',
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
  },
  {
    id: 'ent_03',
    user_id: 'usr_camila_01',
    client_id: 'cli_03',
    service_id: 'srv_perola',
    appointment_id: 'app_03',
    description: 'Sinal Volume Pérola VIP — Juliana Mendes',
    category: 'deposit',
    amount: 50.00,
    payment_method_id: 'pm_credito',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    status: 'received',
    notes: 'Pago via link de cartão',
    created_at: subDays(today, 1).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'ent_04',
    user_id: 'usr_camila_01',
    client_id: 'cli_07',
    service_id: 'srv_rubi',
    appointment_id: 'app_06',
    description: 'Aplicação Volume Rubi — Larissa Alcantara',
    category: 'service',
    amount: 145.00,
    payment_method_id: 'pm_pix',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    status: 'received',
    created_at: subDays(today, 1).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'ent_05',
    user_id: 'usr_camila_01',
    client_id: 'cli_06',
    service_id: 'srv_esmeralda',
    description: 'Aplicação Volume Esmeralda — Fernanda de Oliveira',
    category: 'service',
    amount: 125.00,
    payment_method_id: 'pm_debito',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    status: 'received',
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
  },
  {
    id: 'ent_06',
    user_id: 'usr_camila_01',
    client_id: 'cli_05',
    service_id: 'srv_jade',
    description: 'Aplicação Volume Jade — Gabriela Vasconcelos',
    category: 'service',
    amount: 135.00,
    payment_method_id: 'pm_pix',
    date: format(subDays(today, 5), 'yyyy-MM-dd'),
    status: 'received',
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 5).toISOString(),
  },
  {
    id: 'ent_07',
    user_id: 'usr_camila_01',
    description: 'Venda de Kit Cuidados Pós-Lash (Espuma Neutra + Escovinhas)',
    category: 'product',
    amount: 45.00,
    payment_method_id: 'pm_dinheiro',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    status: 'received',
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
  },
  // Contas a Receber (Pendente)
  {
    id: 'ent_08',
    user_id: 'usr_camila_01',
    client_id: 'cli_03',
    service_id: 'srv_perola',
    appointment_id: 'app_03',
    description: 'Saldo Restante Volume Pérola VIP — Juliana Mendes',
    category: 'service',
    amount: 100.00,
    payment_method_id: 'pm_pix',
    date: todayStr,
    due_date: todayStr,
    status: 'pending',
    notes: 'A receber no estúdio após conclusão',
    created_at: today.toISOString(),
    updated_at: today.toISOString(),
  },
  {
    id: 'ent_09',
    user_id: 'usr_camila_01',
    client_id: 'cli_05',
    service_id: 'srv_cristal',
    appointment_id: 'app_04',
    description: 'Aplicação Volume Cristal — Gabriela Vasconcelos',
    category: 'service',
    amount: 120.00,
    payment_method_id: 'pm_pix',
    date: todayStr,
    due_date: todayStr,
    status: 'pending',
    created_at: today.toISOString(),
    updated_at: today.toISOString(),
  },
];

export const initialFinancialExpenses: FinancialExpense[] = [
  {
    id: 'exp_01',
    user_id: 'usr_camila_01',
    category_id: 'exp_aluguel',
    description: 'Aluguel do Studio — Sala Cristiano Angeli',
    amount: 1100.00,
    cost_type: 'fixed',
    payment_method_id: 'pm_pix',
    supplier: 'Imobiliária Assunção',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    is_recurring: true,
    recurrence_interval: 'monthly',
    recurrence_day: 5,
    status: 'paid',
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
  },
  {
    id: 'exp_02',
    user_id: 'usr_camila_01',
    category_id: 'exp_internet',
    description: 'Internet Fibra Óptica 500MB',
    amount: 119.90,
    cost_type: 'fixed',
    payment_method_id: 'pm_debito',
    supplier: 'Vivo Fibra',
    date: format(subDays(today, 6), 'yyyy-MM-dd'),
    is_recurring: true,
    recurrence_interval: 'monthly',
    recurrence_day: 10,
    status: 'paid',
    created_at: subDays(today, 6).toISOString(),
    updated_at: subDays(today, 6).toISOString(),
  },
  {
    id: 'exp_03',
    user_id: 'usr_camila_01',
    category_id: 'exp_materiais',
    description: 'Reposição Colas de Secagem Rápida (Nagaraku & Rastelli)',
    amount: 240.00,
    cost_type: 'variable',
    payment_method_id: 'pm_credito',
    supplier: 'Lash Shop SP',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    is_recurring: false,
    status: 'paid',
    created_at: subDays(today, 4).toISOString(),
    updated_at: subDays(today, 4).toISOString(),
  },
  {
    id: 'exp_04',
    user_id: 'usr_camila_01',
    category_id: 'exp_fios',
    description: 'Caixas de Fios Tecnológicos 0.07 e 0.05 Curvaturas C e D',
    amount: 180.00,
    cost_type: 'variable',
    payment_method_id: 'pm_pix',
    supplier: 'Distribuidora Elite Lashes',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    is_recurring: false,
    status: 'paid',
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
  },
  {
    id: 'exp_05',
    user_id: 'usr_camila_01',
    category_id: 'exp_marketing',
    description: 'Anúncios Instagram Ads — Região São Bernardo',
    amount: 150.00,
    cost_type: 'variable',
    payment_method_id: 'pm_credito',
    supplier: 'Meta Ads',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    is_recurring: true,
    recurrence_interval: 'monthly',
    status: 'paid',
    created_at: subDays(today, 1).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'exp_06',
    user_id: 'usr_camila_01',
    category_id: 'exp_energia',
    description: 'Conta de Energia Elétrica (Enel)',
    amount: 135.50,
    cost_type: 'fixed',
    payment_method_id: 'pm_pix',
    supplier: 'Enel SP',
    date: todayStr,
    due_date: format(addDays(today, 5), 'yyyy-MM-dd'),
    is_recurring: true,
    recurrence_interval: 'monthly',
    recurrence_day: 15,
    status: 'pending',
    created_at: today.toISOString(),
    updated_at: today.toISOString(),
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif_01',
    user_id: 'usr_camila_01',
    title: 'Atendimento Próximo',
    message: 'Juliana Mendes tem horário marcado às 14:00 (Volume Pérola VIP).',
    type: 'appointment',
    is_read: false,
    link: '/agenda',
    created_at: today.toISOString(),
  },
  {
    id: 'notif_02',
    user_id: 'usr_camila_01',
    title: 'Google Calendar Conectado',
    message: 'Agenda sincronizada com sucesso com a conta Google.',
    type: 'success',
    is_read: true,
    link: '/configuracoes',
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'notif_03',
    user_id: 'usr_camila_01',
    title: 'Conta a Vencer',
    message: 'Conta Enel (R$ 135,50) vence nos próximos dias.',
    type: 'financial',
    is_read: false,
    link: '/financeiro',
    created_at: today.toISOString(),
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_01',
    user_id: 'usr_camila_01',
    entity_type: 'appointment',
    entity_id: 'app_01',
    action: 'update',
    description: 'Camila concluiu o atendimento de Mariana Silva (Volume Jade).',
    changes: { status: { from: 'in_progress', to: 'completed' } },
    created_at: today.toISOString(),
    user_email: 'camila@camilarodriguesbeauty.com.br',
  },
  {
    id: 'log_02',
    user_id: 'usr_camila_01',
    entity_type: 'financial_entry',
    entity_id: 'ent_01',
    action: 'create',
    description: 'Entrada financeira de R$ 85,00 gerada automaticamente ao concluir atendimento.',
    created_at: today.toISOString(),
    user_email: 'camila@camilarodriguesbeauty.com.br',
  },
  {
    id: 'log_03',
    user_id: 'usr_camila_01',
    entity_type: 'service',
    entity_id: 'srv_jade',
    action: 'update',
    description: 'Camila atualizou preço do Volume Jade de R$ 130,00 para R$ 135,00.',
    changes: { price: { from: 130.00, to: 135.00 } },
    created_at: subDays(today, 2).toISOString(),
    user_email: 'camila@camilarodriguesbeauty.com.br',
  },
];

export const initialGoogleCalendarConnection: GoogleCalendarConnection = {
  id: 'gcal_conn_01',
  user_id: 'usr_camila_01',
  is_connected: true,
  google_account_email: 'camilarodrigues.studio@gmail.com',
  last_sync_at: today.toISOString(),
  sync_status: 'success',
  sync_message: 'Sincronização realizada com sucesso.',
  created_at: '2026-02-01T10:00:00Z',
  updated_at: today.toISOString(),
};
